### ISSUE TITLE
Isomorphic reflux blocking install of ambidex via npm

### ISSUE THREAD

**Issue by KraigWalker** [appsforartists/isomorphic-reflux#1]
npm ERR! notarget No compatible version found: isomorphic-reflux@'0.2.5.1'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.2.1"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by appsforartists** [comment]
Sorry about that.  Just published it as 0.2.5.
